apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: test-component--wnid
  namespace: build-templates-e2e
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: test-app-ptds
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: test-component--wnid
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: test-component--wnid-
      labels:
        build.appstudio.openshift.io/application: test-app-ptds
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: test-component--wnid
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: build-templates-e2e
    spec:
      params:
      - name: git-url
        value: https://github.com/redhat-appstudio-qe/devfile-sample-python-basic
      - name: output-image
        value: quay.io/redhat-appstudio/test-images:c2dd0434e1ff45aa9e6b05f8e75b4db1-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/pull-request-builds:base-4bf9fdd9bb982bbb7915e7c49732250e8efa8c06
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: test-component--wnid/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
