apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component--wnid
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component--wnid
    app.kubernetes.io/part-of: test-app-ptds
  name: test-component--wnid
  namespace: build-templates-e2e
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-component--wnid
    weight: 100
status: {}
